version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: olapdb
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123 # For HTTP
      - 9000:9000 # For native client
    volumes:
      - data:/var/lib/clickhouse/
      - logs:/var/log/clickhouse-server/

volumes:
  data:
  logs: